name: MiniC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linting Tools
        run: |
          sudo apt update --yes
          sudo apt install --yes clang-format cppcheck

      - name: Run clang-format
        run: |
          find . \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" -o -name "*.hxx" -o -name "*.inl" \) \
          -not -path "*/build*/*" | xargs clang-format -style=file --dry-run --Werror

      - name: Run Cppcheck
        run: |
          # --library=googletest: Pomaga zrozumieć makra TEST_F, EXPECT_EQ itp.
          # -DTEST_F(A,B)=void A##B(): "Zaślepkowe" definicje makr, jeśli biblioteka nie wystarczy.
          # -I include: Wskazuje folder z nagłówkami (dostosuj, jeśli masz inną nazwę).
          cppcheck --enable=all \
            --suppress=unusedFunction \
            --suppress=missingIncludeSystem \
            --library=googletest \
            --inline-suppr \
            --error-exitcode=1 \
            -I include \
            . -i build/

  build-and-test:
    needs: static-analysis
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [14, 15]
        build_type: [Debug, Release]
    
    container: gcc:${{ matrix.gcc_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          apt update --yes
          apt install --yes cmake clang-tidy

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DUSE_SANITIZERS=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }} \
            -DBUILD_TESTS=ON \
            -DBUILD_BENCHMARKS=${{ matrix.build_type == 'Release' && 'ON' || 'OFF' }} \
            -DPRODUCTION=${{ matrix.build_type == 'Release' && 'ON' || 'OFF' }}

      - name: Build
        run: |
          cmake --build build -j $(nproc)

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure